apiVersion: apps/v1
kind: Deployment
metadata:
  name: capston-depl-VERSION
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 2
  template:
    metadata:
      annotations:
        forceRedeployUniqId: VERSION
      labels:
        app: react-app
        version: VERSION
    spec:
      containers:
        - name: react-app
          image: heratdhruv/capston:VERSION
